language: r
sudo: false
dist: trusty
cache: packages

env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=0  # no error if suggested packs are not avail
    - _R_CHECK_TESTS_NLINES_=999
    - R_MAX_NUM_DLLS=999
    - WARMUPPKGS='roxygen2 knitr shiny '
    
warnings_are_errors: true
r_check_args: "--as-cran --run-donttest"

r_github_packages:
  - berndbischl/BBmisc
  - jimhester/lintr
  
 jobs:
  include:
    - stage: warmup-1
      install:
        - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0) install.packages("devtools")'
        - Rscript -e 'devtools::install_deps()'
        - Rscript -e 'pkgs = trimws(strsplit(Sys.getenv("WARMUPPKGS"), " ")[[1]]); pkgs = pkgs[!pkgs %in% installed.packages()]; if (length(pkgs) > 0) install.packages(pkgs)'
      script: true
    - stage: warmup-2
      install:
        - Rscript -e 'devtools::install_deps(upgrade = TRUE, dependencies = TRUE)'
      script: true
    - stage: check
      before_script:
        - R --no-save <<< 'library("devtools"); document()'
      script:
        - |
          R CMD build .
          travis_wait 100 R CMD check bechmarkVis*.tar.gz --as-cran --run-donttest
        - grep -q -R "WARNING" "benchmarkVis.Rcheck/00check.log" ; [ $? -ne 0 ]
      after_script:
        - ../../travis-tool.sh dump_logs
        
notifications:
  email:
    recipients:
      - collin.leiber@campus.lmu.de
on_success: change
on_failure: always