language: r
    
warnings_are_errors: true

r_github_packages:
  - berndbischl/BBmisc
  - jimhester/lintr
        
notifications:
  email:
    recipients:
      - collin.leiber@campus.lmu.de
on_success: change
on_failure: always